name: Validate Design Docs

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - 'projects/**'
      - 'journeys/**'
      - 'schemas/**'
      - 'scripts/**'
      - 'package.json'
      - 'package-lock.json'
  push:
    branches: [ main, master ]
    paths:
      - 'projects/**'
      - 'journeys/**'
      - 'schemas/**'
      - 'scripts/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  validate:
    name: Validate Design Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run full validation
        run: npm run validate

      - name: Validate cross-references
        run: npm run validate:cross
